####   k3_m5_L3: Final Assignment: Database Querying using SQLite
#####  Author  : LiR
###### Date    : 04.03.2026
Understand the datasets
To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

Socioeconomic Indicators in Chicago
Chicago Public Schools
Chicago Crime Data
1. Socioeconomic Indicators in Chicago
This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2

2. Chicago Public Schools
This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t

Download the datasets
This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet.

Use the links below to read the data files using the Pandas library.

Chicago Census Data
https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

Chicago Public Schools
https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

Chicago Crime Data
https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

NOTE: Ensure you use the datasets available on the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

Execute the below code cell to install the required libraries

In [13]:
!pip install pandas
!pip install ipython-sql prettytable 

import prettytable

prettytable.DEFAULT = 'DEFAULT'

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\dev_soft\anaconda3_2023\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\rusla\appdata\roaming\python\python311\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\dev_soft\anaconda3_2023\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ipython-sql in c:\users\rusla\appdata\roaming\python\python311\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\rusla\appdata\roaming\python\python311\site-packages (3.17.0)
Requirement already satisfied: ipython in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython-sql) (2.0.43)
Requirement already satisfied: sqlparse in c:\users\rusla\appdata\roaming\python\python311\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\rusla\appdata\roaming\python\python311\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\dev_soft\anaconda3_2023\lib\site-packages (from prettytable) (0.2.13)
Requirement already satisfied: greenlet>=1 in c:\dev_soft\anaconda3_2023\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: decorator in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack-data in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\dev_soft\anaconda3_2023\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: executing>=1.2.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from stack-data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from stack-data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in c:\dev_soft\anaconda3_2023\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.3)

In [14]:
#Store the datasets in database tables
#To analyze the data using SQL, it first needs to be loaded into SQLite DB. We will create three tables in as under:

#CENSUS_DATA
#CHICAGO_PUBLIC_SCHOOLS
#CHICAGO_CRIME_DATA
#Load the pandas and sqlite3 libraries and establish a connection to FinalDB.db

In [15]:
import os
print(os.getcwd())
print(os.listdir())

c:\SourceCode\PSC\2025\coursera\3_SQL_DataSceince
['csv', 'DB', 'FilmLocations.csv', 'films.db', 'INSTRUCTOR.db', 'k2_L4_CREAT_ALTER_TRUNCATE_DROP.ipynb', 'k3_L1_Select.ipynb', 'k3_L2_COUNT_DISTINCT_LIMIT.ipynb', 'k3_L3_ins_upd_del.ipynb', 'k3_L5_SQL_Scripts.ipynb', 'k3_L6_str_pattern_sort_group.ipynb', 'k3_L7_BuiltInFunct_Date.ipynb', 'k3_L8_Sub_queries.ipynb', 'k3_L9_Multi_Tbl.ipynb', 'k3_m4_L1_Cr_tbl_ins_query.ipynb', 'k3_m4_L2_SQL_magic.ipynb', 'k3_m4_L3_RealDataSet.ipynb', 'k3_m5_L1_real world data-set.ipynb', 'k3_m5_L3_final.ipynb', 'Lab', 'socioeconomic.db', 'sp_k3_L5_1_drop_tbl.sql', 'sp_k3_L5_2_alter_tbl.sql', 'sp_k3_L6_cr_tbl.sql', 'sp_k3_L7_PETRESCUE-CREATE.sql', 'sp_k3_L8_Script_Create_Tables.sql', 'SQLiteMagic.db']

In [28]:
import csv, sqlite3
#or
import os, sqlite3
os.makedirs("DB", exist_ok=True)
con = sqlite3.connect("DB/FinalDB.db")
# from current catalog - con = sqlite3.connect(".DB/FinalDB.db") 
# from ROOT catalog    -  con = sqlite3.connect("//DB/FinalDB.db") 
con = sqlite3.connect("DB/FinalDB.db")
cur = con.cursor()

In [17]:
# SQl Magik install 
!pip install ipython-sql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ipython-sql in c:\users\rusla\appdata\roaming\python\python311\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\rusla\appdata\roaming\python\python311\site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython-sql) (2.0.43)
Requirement already satisfied: sqlparse in c:\users\rusla\appdata\roaming\python\python311\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\rusla\appdata\roaming\python\python311\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in c:\dev_soft\anaconda3_2023\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: decorator in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack-data in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\dev_soft\anaconda3_2023\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\dev_soft\anaconda3_2023\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\dev_soft\anaconda3_2023\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: executing>=1.2.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from stack-data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\dev_soft\anaconda3_2023\lib\site-packages (from stack-data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in c:\dev_soft\anaconda3_2023\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.3)

In [18]:
#df or
#%sql select * from ChicagoPublicSchools_DATA
%sql select count(*) from  ChicagoPublicSchools_DATA where TRIM([Elementary, Middle, or High School])='ES';
#%sql select count(*) 
#from ChicagoPublicSchools_DATA 
#where TRIM([Elementary, Middle, or High School"]) = 'ES';

UsageError: Line magic function `%sql` not found.

In [19]:
%load_ext sql

In [20]:
# Verbinden SQL-Magik mit DB/FinalDB.db
#sqlite:///FinalDB.db	файл в текущей папке
#sqlite:///DB/FinalDB.db	файл в папке DB
#sqlite:////полный/путь/db.db
%sql sqlite:///DB/FinalDB.db

In [21]:
# Store the dataset in a Table
import pandas as pd
#df_final = pandas.read_csv('csv/m5_L1/ChicagoPublicSchools.csv')
df_final = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
df_final.to_sql("CHICAGO_CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

df_final = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
df_final.to_sql("CHICAGO_PUBLIC_SCHOOLS", con, if_exists='replace', index=False,method="multi")

df_final = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
df_final.to_sql("CHICAGO_CRIME_DATA", con, if_exists='replace', index=False,method="multi")
#df_final

533

In [ ]:
#df_final

In [ ]:
#reload_ext sql wenn BAg ist
%load_ext sql
%sql sqlite:///DB/FinalDB.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [ ]:
# %%sql вместо %sql ein BAG
#%sql SELECT name FROM sqlite_master WHERE type='table';
#OR
#%%sql
#SELECT name FROM sqlite_master WHERE type='table'
#OR
#import sqlite3, pandas as pd

#con = sqlite3.connect("DB/FinalDB.db")
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", con)

                     name
0     CHICAGO_CENSUS_DATA
1  CHICAGO_PUBLIC_SCHOOLS
2      CHICAGO_CRIME_DATA

In [ ]:
#%sql SELECT COUNT(*) FROM CHICAGO_CRIME_DATA;
#%sql SELECT COUNT(*) FROM CHICAGO_PUBLIC_SCHOOLS;
#%sql SELECT COUNT(*) FROM CHICAGO_CENSUS_DATA;
#OR
sql_query = 'SELECT COUNT(*) FROM CHICAGO_CRIME_DATA'
pd.read_sql_query(sql_query, con)
sql_query = 'SELECT COUNT(*) FROM CHICAGO_PUBLIC_SCHOOLS'
pd.read_sql_query(sql_query, con)
sql_query = 'SELECT COUNT(*) FROM CHICAGO_CENSUS_DATA'
pd.read_sql_query(sql_query, con)

   COUNT(*)
0        78

In [ ]:
sql_query = """
            SELECT 
                (SELECT COUNT(*) FROM CHICAGO_CRIME_DATA) AS count_CHICAGO_CRIME_DATA,
                (SELECT COUNT(*) FROM CHICAGO_PUBLIC_SCHOOLS) AS count_CHICAGO_PUBLIC_SCHOOLS,
                (SELECT COUNT(*) FROM CHICAGO_CENSUS_DATA) AS count_CHICAGO_CENSUS_DATA
            """
pd.read_sql_query(sql_query, con)

,count_CHICAGO_CRIME_DATA,count_CHICAGO_PUBLIC_SCHOOLS,count_CHICAGO_CENSUS_DATA
0,533,566,78

In [ ]:
#Problem 1 Find the total number of crimes recorded in the CRIME table.
#%sql SELECT COUNT(*) FROM CHICAGO_CRIME_DATA

In [ ]:
#cписок полей
#%sql PRAGMA table_info(CHICAGO_CENSUS_DATA);
pd.read_sql_query("PRAGMA table_info(CHICAGO_CENSUS_DATA);", con)

,cid,name,type,notnull,dflt_value,pk
0,0,COMMUNITY_AREA_NUMBER,REAL,0,None,0
1,1,COMMUNITY_AREA_NAME,TEXT,0,None,0
2,2,PERCENT_OF_HOUSING_CROWDED,REAL,0,None,0
3,3,PERCENT_HOUSEHOLDS_BELOW_POVERTY,REAL,0,None,0
4,4,PERCENT_AGED_16__UNEMPLOYED,REAL,0,None,0
5,5,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,REAL,0,None,0
6,6,PERCENT_AGED_UNDER_18_OR_OVER_64,REAL,0,None,0
7,7,PER_CAPITA_INCOME,INTEGER,0,None,0
8,8,HARDSHIP_INDEX,REAL,0,None,0

In [ ]:
#Problem 2 List community area names and numbers with per PER_CAPITA_INCOME less than 11000
#COMMUNITY_AREA_NUMBER LOCATION_DESCRIPTION
#sql_query ='select cd.COMMUNITY_AREA_NUMBER, cd.LOCATION_DESCRIPTION, \
            #from  CHICAGO_CENSUS_DATA as d, \
             #     CHICAGO_CRIME_DATA as cd  \
            #WHERE d.COMMUNITY_AREA_NUMBER = cd.COMMUNITY_AREA_NUMBER \
             #     and d.PER_CAPITA_INCOME < 11000 LIMIT 2 '
sql_query = ' select COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME, PER_CAPITA_INCOME \
                from CHICAGO_CENSUS_DATA \
                WHERE PER_CAPITA_INCOME < 11000 ' #LIMIT 2 '
pd.read_sql_query(sql_query, con)

   COMMUNITY_AREA_NUMBER COMMUNITY_AREA_NAME  PER_CAPITA_INCOME
0                   26.0  West Garfield Park              10934
1                   30.0      South Lawndale              10402
2                   37.0         Fuller Park              10432
3                   54.0           Riverdale               8201

In [ ]:

pd.read_sql_query("PRAGMA table_info(CHICAGO_CRIME_DATA);", con)
pd.read_sql_query("PRAGMA table_info(CHICAGO_PUBLIC_SCHOOLS);", con)
pd.read_sql_query("PRAGMA table_info(CHICAGO_CENSUS_DATA);", con)

sql_query = " select ccd.ID,ccd.CASE_NUMBER,ccd.DATE,cps.NAME_OF_SCHOOL,cps.Street_Address \
                from CHICAGO_PUBLIC_SCHOOLS as cps, \
                CHICAGO_CRIME_DATA as ccd \
                where [Elementary, Middle, or High School] = 'MS' \
                      and ccd.ARREST > 0 LIMIT 2"
pd.read_sql_query(sql_query, con)

,ID,CASE_NUMBER,DATE,NAME_OF_SCHOOL,Street_Address
0,4494340,HL793243,2005-12-16,Albany Park Multicultural Academy,4929 N Sawyer Ave
1,4494340,HL793243,2005-12-16,Ames Middle School,1920 N Hamlin Ave

In [ ]:
#Problem 3 List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)
#%sql  SELECT CASE_NUMBER \
#      FROM CHICAGO_CRIME_DATA \
#      WHERE DESCRIPTION LIKE '%MINOR%'

sql_query = """
SELECT CASE_NUMBER,DESCRIPTION
FROM CHICAGO_CRIME_DATA
WHERE DESCRIPTION LIKE '%MINOR%'
"""
pd.read_sql_query(sql_query, con)

  CASE_NUMBER                    DESCRIPTION
0    HL266884  SELL/GIVE/DEL LIQUOR TO MINOR
1    HK238408   ILLEGAL CONSUMPTION BY MINOR

In [ ]:
#условие	значение
#PRIMARY_TYPE = 'KIDNAPPING'	преступление — похищение
#DESCRIPTION LIKE '%CHILD%'	в описании упоминается ребёнок
sql_query = """
SELECT CASE_NUMBER,PRIMARY_TYPE	,DESCRIPTION
FROM CHICAGO_CRIME_DATA
WHERE PRIMARY_TYPE = 'KIDNAPPING' and DESCRIPTION LIKE '%CHILD%'
"""
pd.read_sql_query(sql_query, con)

  CASE_NUMBER PRIMARY_TYPE               DESCRIPTION
0    HN144152   KIDNAPPING  CHILD ABDUCTION/STRANGER

In [ ]:
#Problem 5 List the kind of crimes that were recorded at schools. (No repetitions)
#PRIMARY_TYPE	вид преступления
#DISTINCT	убрать повторения
#LOCATION_DESCRIPTION	где произошло
#LIKE '%SCHOOL%'	ищем слово school
sql_query = """ SELECT DISTINCT CASE_NUMBER,DATE,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION
                FROM CHICAGO_CRIME_DATA
                where LOCATION_DESCRIPTION like '%school%' limit 5
            """
pd.read_sql_query(sql_query, con)

,CASE_NUMBER,DATE,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION
0,HL353697,2005-05-04,BATTERY,SIMPLE,"SCHOOL, PUBLIC, GROUNDS"
1,HL725506,2005-11-09,BATTERY,PRO EMP HANDS NO/MIN INJURY,"SCHOOL, PUBLIC, BUILDING"
2,HP716225,2008-12-04,BATTERY,SIMPLE,"SCHOOL, PUBLIC, BUILDING"
3,HH639427,2002-09-10,BATTERY,SIMPLE,"SCHOOL, PUBLIC, BUILDING"
4,JA460432,2017-10-05,BATTERY,SIMPLE,"SCHOOL, PUBLIC, GROUNDS"

In [ ]:
import pandas as pd
#Problem 6 List the type of schools along with the average safety score for each type.
#cps.[Elementary, Middle, or High School],NAME_OF_SCHOOL
sql_query = """ SELECT ccd.HARDSHIP_INDEX, \
                       [Elementary, Middle, or High School] AS school_type, \
                       AVG(cps.SAFETY_SCORE) AS avg_safety_score \
                FROM CHICAGO_CENSUS_DATA as ccd, \
                     CHICAGO_CRIME_DATA as cd, \
                     CHICAGO_PUBLIC_SCHOOLS as cps \
                where ccd.HARDSHIP_INDEX > 0 \
                Group by [Elementary, Middle, or High School] limit 5  
            """
pd.read_sql_query(sql_query, con)

#or
#%sql SELECT
#        cps.[Elementary, Middle, or High School] AS school_type,
#        AVG(cps.SAFETY_SCORE) AS avg_safety_score
#     FROM CHICAGO_PUBLIC_SCHOOLS AS cps
#     JOIN CHICAGO_CENSUS_DATA AS ccd
#     ON   cps.COMMUNITY_AREA_NUMBER = ccd.COMMUNITY_AREA_NUMBER \
#     НЕ НУЖНО ДЛЯ AVG where  ccd.HARDSHIP_INDEX > 0 \
#     GROUP BY cps.[Elementary, Middle, or High School];

   HARDSHIP_INDEX school_type  avg_safety_score
0            39.0          ES         49.520384
1            39.0          HS         49.623529
2            39.0          MS         48.000000

In [ ]:
# сортировка по убыванию DESC
# по возрастанию SELECT * FROM имя_таблицы ORDER BY имя_столбца ASC
sql_query = """ SELECT ccd.PERCENT_HOUSEHOLDS_BELOW_POVERTY, ccd.COMMUNITY_AREA_NAME \
                FROM CHICAGO_CENSUS_DATA as ccd
                ORDER By ccd.PERCENT_HOUSEHOLDS_BELOW_POVERTY    DESC  \
                limit 5  
            """
pd.read_sql_query(sql_query, con)

   PERCENT_HOUSEHOLDS_BELOW_POVERTY COMMUNITY_AREA_NAME
0                              56.5           Riverdale
1                              51.2         Fuller Park
2                              46.6           Englewood
3                              43.1      North Lawndale
4                              42.4  East Garfield Park

In [ ]:
#Which community area number has the most criminal incidents (most crime-prone)?
sql_query = """ SELECT COMMUNITY_AREA_NUMBER
                FROM CHICAGO_CRIME_DATA
                GROUP BY COMMUNITY_AREA_NUMBER
                ORDER BY COUNT(*) DESC
                LIMIT 1; 
            """
pd.read_sql_query(sql_query, con)
#%sql SELECT COMMUNITY_AREA_NUMBER
#FROM CHICAGO_CRIME_DATA
#ROUP BY COMMUNITY_AREA_NUMBER
#HAVING COUNT(*) = (
#    SELECT MAX(cnt)
#    FROM (
#        SELECT COUNT(*) AS cnt
#        FROM CHICAGO_CRIME_DATA
#        GROUP BY COMMUNITY_AREA_NUMBER
#    )
#);

   COMMUNITY_AREA_NUMBER
0                   25.0

In [23]:
#Problem 9 Use a sub-query to find the name of the community area with highest hardship index
sql_query = """ SELECT COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,HARDSHIP_INDEX \
                FROM CHICAGO_CENSUS_DATA 
                where HARDSHIP_INDEX = (select MAX(HARDSHIP_INDEX) from CHICAGO_CENSUS_DATA)
            """
pd.read_sql_query(sql_query, con)

   COMMUNITY_AREA_NUMBER COMMUNITY_AREA_NAME  HARDSHIP_INDEX
0                   54.0           Riverdale            98.0

In [ ]:
#Problem 10 Use a sub-query to determine the Community Area Name with most number of crimes?
sql_query = """ SELECT distinct id, COMMUNITY_AREA_NAME,mAX(count_crime_COMMUNITY)
                FROM(
                SELECT ccd.ID, d.COMMUNITY_AREA_NAME,count (ccd.ID) as count_crime_COMMUNITY  \
                FROM CHICAGO_CRIME_DATA as ccd join CHICAGO_CENSUS_DATA as d \
                on   ccd.COMMUNITY_AREA_NUMBER=d.COMMUNITY_AREA_NUMBER\
                group by ccd.COMMUNITY_AREA_NUMBER \
                order by count_crime_COMMUNITY desc \
                ) 
                
            """
pd.read_sql_query(sql_query, con)
# or via LIMIT 1 without mAX(count_crime_COMMUNITY)
#sql_query = """ SELECT distinct id, COMMUNITY_AREA_NAME
#                FROM(
#                SELECT ccd.ID, d.COMMUNITY_AREA_NAME,count (ccd.ID) as count_crime_COMMUNITY  \
#                FROM CHICAGO_CRIME_DATA as ccd join CHICAGO_CENSUS_DATA as d \
#                on   ccd.COMMUNITY_AREA_NUMBER=d.COMMUNITY_AREA_NUMBER\
#                group by ccd.COMMUNITY_AREA_NUMBER \
#                order by count_crime_COMMUNITY desc \
#                LIMIT 1
#                ) 
                
#            """

NameError: name 'pd' is not defined

In [22]:
#What is the total number of crimes recorded in the CRIME table?
sql_query = """ SELECT count(*) \
                FROM CHICAGO_CRIME_DATA 
            """
pd.read_sql_query(sql_query, con)

   count(*)
0       533

In [24]:
#Which of the following is the correct query to list community areas (name and number) with per capita income less than 11000?
sql_query = """ SELECT count(*) \
                FROM CHICAGO_CRIME_DATA 
            """
pd.read_sql_query(sql_query, con)

   count(*)
0       533

In [48]:
#Команда DESCRIBE используется, чтобы посмотреть структуру таблицы
#import csv, sqlite3
#or
#import os, sqlite3
import pandas as pd
con = sqlite3.connect("DB/FinalDB.db")
#cur = con.cursor()
#sql_query = """ DESCRIBE CHICAGO_CRIME_DATA""" # MySQL
#sql_query = "PRAGMA table_info(CHICAGO_CRIME_DATA)"
sql_query = "sELECT DISTINCT COMMUNITY_AREA_NUMBER,  COUNT(COMMUNITY_AREA_NUMBER) fROM CHICAGO_CRIME_DATA  GROUP BY COMMUNITY_AREA_NUMBER"
pd.read_sql_query(sql_query, con)

    COMMUNITY_AREA_NUMBER  COUNT(COMMUNITY_AREA_NUMBER)
0                     NaN                             0
1                     1.0                             6
2                     2.0                             7
3                     3.0                             4
4                     4.0                             3
..                    ...                           ...
66                   72.0                             4
67                   73.0                             3
68                   75.0                             1
69                   76.0                             4
70                   77.0                             2

[71 rows x 2 columns]